package com.sysdelphia.hibernate.proto;
// Generated May 26, 2007 6:24:08 PM by Hibernate Tools 3.2.0.b9



/**
 * Name generated by hbm2java
 */
public class Name  implements java.io.Serializable {


     private String firstName;
     private String initial;
     private String lastName;

    public Name() {
    }

    public Name(String firstName, String initial, String lastName) {
       this.firstName = firstName;
       this.initial = initial;
       this.lastName = lastName;
    }
   
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getInitial() {
        return this.initial;
    }
    
    public void setInitial(String initial) {
        this.initial = initial;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }




}


