package com.sysdelphia.hibernate.proto;
// Generated May 26, 2007 6:24:08 PM by Hibernate Tools 3.2.0.b9


import java.util.ArrayList;
import java.util.List;

/**
 * WorkItem generated by hbm2java
 */
public class WorkItem  implements java.io.Serializable {


     private long id;
     private User assignedTo;
     private String description;
     private int priority;
     private String status;
     private List<Note> notes = new ArrayList<Note>(0);

    public WorkItem() {
    }

    public WorkItem(User assignedTo, String description, int priority, String status, List<Note> notes) {
       this.assignedTo = assignedTo;
       this.description = description;
       this.priority = priority;
       this.status = status;
       this.notes = notes;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public User getAssignedTo() {
        return this.assignedTo;
    }
    
    public void setAssignedTo(User assignedTo) {
        this.assignedTo = assignedTo;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public List<Note> getNotes() {
        return this.notes;
    }
    
    public void setNotes(List<Note> notes) {
        this.notes = notes;
    }




}


