package com.sysdelphia.hibernate.proto;
// Generated May 26, 2007 6:24:08 PM by Hibernate Tools 3.2.0.b9


import java.util.Collection;

/**
 * Catalog generated by hbm2java
 */
public class Catalog  implements java.io.Serializable {


     private long id;
     private String name;
     private String description;
     private Collection<String> entries;

    public Catalog() {
    }

	
    public Catalog(String name) {
        this.name = name;
    }
    public Catalog(String name, String description, Collection<String> entries) {
       this.name = name;
       this.description = description;
       this.entries = entries;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Collection<String> getEntries() {
        return this.entries;
    }
    
    public void setEntries(Collection<String> entries) {
        this.entries = entries;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Catalog) ) return false;
		 Catalog castOther = ( Catalog ) other; 
         
		 return ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         
         
         
         
         return result;
   }   


}


